import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import ConvexClientProvider from "@/providers/convex-client-provider";
import { TooltipProvider } from "@workspace/ui/components/tooltip";
import localFont from "next/font/local";

const helveticaNow = localFont({
  src: "../fonts/HelveticaNowVar.woff2",
  variable: "--font-helvetica-now",
});

const ballet = localFont({
  src: "../fonts/Ballet.woff2",
  variable: "--font-ballet",
});

const ppEditorial = localFont({
  src: "../fonts/ppeditorialold.woff2",
  variable: "--font-pp-editorial",
});

const someTypeMono = localFont({
  src: "../fonts/SometypeMono.woff2",
  variable: "--font-some-type-mono",
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-helvetica-now ${ppEditorial.variable} ${helveticaNow.variable} ${ballet.variable} ${someTypeMono.variable}`}
      >
        <ClerkProvider>
          <ConvexClientProvider>
            <TooltipProvider>
              <div className="w-full min-h-screen flex items-center justify-center bg-[#f5f5f5]">
                {children}
              </div>
            </TooltipProvider>
          </ConvexClientProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
